#ifndef THEME_H
#define THEME_H

// #define BACKGROUND_COLOR TFT_BLACK
#define BACKGROUND_COLOR TFT_VIOLET
#define TEXT_COLOR TFT_WHITE
#define HIGHLIGHT_COLOR TFT_YELLOW
#define TEMP_COLOR TFT_RED
#define HUMIDITY_COLOR TFT_BLUE
#define PRESSURE_COLOR TFT_GREEN
#define WIND_COLOR TFT_CYAN

// Add more colors as needed for your theme
#endif
